config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders
  resources :lineitems
  resources :carts

  get 'login', to: 'access#new', as: 'login'
  post 'login', to: 'access#create'
  get 'admin', to: 'admin#index', as: 'admin'
  delete 'logout', to: 'access#destroy', as: 'logout'

  get 'shopper/index'
  post 'shopper/index'

  root "shopper#index", as: "shopper"
  
  resources :products
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :lineitems, dependent: :destroy

    def add_item(product_id)
        curr_item = self.lineitems.find_by(product_id: product_id)
        if curr_item
            curr_item.quantity += 1
        else
            curr_item = self.lineitems.build(product_id: product_id)
        end
        curr_item
    end

    def total_price
        self.lineitems.to_a.sum {|item| item.item_total_price}
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to shopper_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<p id="notice"><%= notice %></p>

<h3>Items in your shopping cart </h3>

<table>
    <% @cart.lineitems.each do |line| %>
        <tr>
            <td><%= line.quantity %></td>
            <td><%= line.product.name %></td>
            <td><%= line.product.price %></td>
        </tr>
    <% end %>
    <tr>
        <td colspan='2'>Total</td>
        <td><%= @cart.total_price %></td>
    </tr>
</table>

<%= button_to('Empty Cart', @cart, method: :delete, data: {confirm: "Are you sure?"}) %>
<%= button_to('Checkout', new_order_path, method: :get ) %>
<%= button_to('Login', login_url, method: :get ) %>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Items in your shopping cart </h3>

<table>
    <% @cart.lineitems.each do |line| %>
        <tr>
            <td><%= line.quantity %></td>
            <td><%= line.product.name %></td>
            <td><%= line.product.price %></td>
        </tr>
    <% end %>
    <tr>
        <td colspan='2'>Total</td>
        <td><%= @cart.total_price %></td>
    </tr>
</table>

<%= button_to('Empty Cart', @cart, method: :delete, data: {confirm: "Are you sure?"}) %>
<%= button_to('Checkout'), new_order_path, method: :get %>