config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders
  resources :lineitems
  resources :carts

  get 'login', to: 'access#new', as: 'login'
  post 'login', to: 'access#create'
  get 'admin', to: 'admin#index', as: 'admin'
  delete 'logout', to: 'access#destroy', as: 'logout'

  get 'shopper/index'
  post 'shopper/index'

  root "shopper#index", as: "shopper"
  
  resources :products
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PD's Anime Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
    <div id='banner'>
      <%= image_tag("logo.png", height: 50, width: 50) %>
      <%= "Our Products" %>
    </div>
    <div id='columns'>
      <div id='side'>
        <div id='cart'>
          <%= render @cart %>
        </div>
        <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders',   orders_path   %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
        </ul>
        <%= button_to('Logout', logout_path, method: :delete) %>
        <% end %>
      </div>

      <div id='main'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>